#!/bin/zsh
echo -e "\e[1;31mMake sure this repo is cloned in ~/.dotfiles\e[0m"
echo -e "\e[1;31mThis script will overwrite your current dotfiles\e[0m"
echo "Press any key to continue"
read -k1 -s

if [ ! -d "$HOME/.dotfiles" ]; then
  echo -e "\e[1;31mError: This script requires the .dotfiles directory to be located in the home directory.\e[0m"
  echo -e "\e[1;31mPlease make sure the .dotfiles repository is cloned into $HOME/.dotfiles and try again.\e[0m"
  exit 1
fi

# TODO: Test is created symlinks are actually working

DOTFILES_DIR="$HOME/.dotfiles"

# Create symlinks function
create_symlink() {
  ln -s "$DOTFILES_DIR/$1" "$HOME/$2"
}


# Create symlinks
create_symlink .vim/.vimrc .vimrc
create_symlink bash/.bash_aliases .bash_aliases
create_symlink bash/.profile .profile
create_symlink general/.skhdrc .skhdrc
create_symlink general/.yabairc .yabairc
create_symlink git/.gitattributes .gitattributes
create_symlink git/.gitconfig .gitconfig
create_symlink git/.gitignore_global .gitignore_global
create_symlink tmux/.tmux-powerlinerc .tmux-powerlinerc
create_symlink tmux/.tmux.conf .tmux.conf
create_symlink vim/.ideavimrc .ideavimrc
create_symlink zsh/.zshrc .zshrc

echo "All symlinks created successfully!"


# Xcode commandline tools
echo "Installing xcode commandline tools"
xcode-select --install


# Homebrew
echo "Installing brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


# Install homebrew formulae and casks
echo "Installing brew formulae and casks"
brew bundle --file="$HOME/.dotfiles/config/Brewfile"


# set Git preferences
echo "Setting Git defaults"
git config --global user.email "y.gherbi.dev@gmail.com"
git config --global user.name "Yassine Gherbi"
git config --global core.editor 'nvim'



# install TMUX Plugin Manager - TPM
echo "Installing TMUX Plugin Manager - TPM"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


# install nvim package manager
echo "Installing nvim package manager"
git clone https://github.com/wbthomason/packer.nvim ~/.config/nvim/packer.nvim

# install nvm
echo "Installing nvm"
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash


# install global node modules
echo "Installing global node modules"
~/.dotfiles/node/install-global-packages.sh


# install nvim plugins
echo "Installing nvim plugins"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'


# install vim plugins
echo "Installing vim plugins"
vim -c 'PlugInstall' \
  -c 'qa!'
