#!/bin/zsh

# Xcode commandline tools
echo "Installing xcode commandline tools"
xcode-select --install


# Homebrew
echo "Installing brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


# Install homebrew formulae and casks
echo "Installing brew formulae and casks"
brew bundle --file="$HOME/.dotfiles/config/Brewfile"


# set Git preferences
echo "Setting Git defaults"
git config --global user.email "y.gherbi.dev@gmail.com"
git config --global user.name "Yassine Gherbi"
git config --global core.editor 'nvim'
# always use SSH instead of HTTPS for git
git config --global --add url."git@github.com:".insteadOf "https://github.com/"

# install vim plugins
echo "Installing nvim plugins"
nvim -c 'PlugInstall' \
    -c 'qa!'

# install vim plugins
echo "Installing vim plugins"
vim -c 'PlugInstall' \
    -c 'qa!'
