tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"  
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jesseduffield/lazygit"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "oven-sh/bun"
tap "qmk/qmk"
tap "romkatv/powerlevel10k"
tap "shivammathur/php"

# Programming Languages
brew "deno"
brew "nvm"
brew "php"
brew "python"
brew "openjdk@11"

# Dev Tools
brew "android-platform-tools"
brew "bun"
brew "composer"
brew "docker"
brew "fastlane"
brew "gh"
brew "git"
brew "git-quick-stats"
brew "gradle"
brew "jesseduffield/lazygit/lazygit"
brew "mysql@5.7"
brew "nvim"
brew "pnpm"
brew "pyenv"
brew "rbenv"
brew "vim"
brew "watchman"
brew "yarn"
cask "adobe-creative-cloud"
cask "arduino"
cask "flipper"
cask "jetbrains-toolbox"
cask "reactotron"
cask "sourcetree"
cask "virtualbox"
cask "visual-studio-code"
cask "vscodium"
cask "zed"
cask "zulu11"

# Terminal, CLI and Utils
brew "avrdude"
brew "coreutils"
brew "cowsay"
brew "glow"
brew "gnupg"
brew "htop"
brew "iproute2mac"
brew "jq"
brew "lastpass-cli"
brew "lolcat"
brew "mas"
brew "p7zip"
brew "rar"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "stow"
brew "svn"
brew "tmux"
brew "tree"
brew "wimlib"
brew "xdotool"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alacritty"
cask "iterm2"
cask "kitty"
cask "phoenix"


# Web Tools
brew "httpie"
cask "arc"
cask "brave-browser"
cask "firefox"
cask "google-chrome"
cask "google-chrome-canary"
cask "microsoft-edge"
cask "ngrok"
cask "opera-gx"
cask "postman"
cask "tor-browser"


# Design Tools
cask "figma"
cask "zeplin"

# File Storage
cask "dropbox"

# Communication Apps
cask "discord"
cask "microsoft-teams"
cask "slack"
cask "whatsapp"

# Fonts
brew "font-jetbrains-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-juliamono"
cask "font-source-code-pro"


# Keyboard stuff
brew "qmk/qmk/qmk"
cask "karabiner-elements"
cask "qmk-toolbox"
cask "via"
cask "vial"

# Productivity Apps
cask "adobe-acrobat-pro"
cask "alfred"
cask "alt-tab"
cask "cheatsheet"
cask "rectangle"
cask "todoist"
cask "toggl-track"

# Other
brew "evolv-escribe-suite"
brew "trash"
cask "1password"
cask "ankerwork"
cask "authy"
cask "balance-lock" # Because Apple is a piece of shit
cask "balenaetcher"
cask "betterdisplay"
cask "bunqcommunity-bunq"
cask "f-bar"
cask "intel-power-gadget"
cask "keycastr"
cask "lastpass"
cask "little-snitch"
cask "obs"
cask "rar"
cask "raspberry-pi-imager"
cask "setapp"
cask "sidequest"
cask "spotify"

# Cad & 3D
cask "ultimaker-cura"
cask "autodesk-fusion360"
cask "kicad"
cask "lycheeslicer"

# Mac App Store
mas "Backtrack", id: 1477089520
mas "Brother P-touch Editor", id: 1453365242
mas "iTranslate", id: 884952790
mas "Keynote", id: 409183694
mas "LanguageTool", id: 1534275760
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Speedtest", id: 1153157709
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Toggl Track", id: 1291898086
mas "Xcode", id: 497799835
